name    'ispavailability-lumberjack'
version '0.0.1'
source 'https://github.com/electrical/puppet-lumberjack'
author 'ispavailability'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring lumberjack'
description 'Module for managing and configuring lumberjack'
project_page 'https://github.com/electrical/puppet-lumberjack'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
